#!/bin/bash

while true; do
  if [ $(ls tmp | grep -c "\.osm") -eq 0 ]; then
    sleep 10
  else
    while [ -e next.osm ]; do
      sleep 10
    done
	  for file in $(ls tmp | grep "\.osm"); do
      while [ $(ls tmp | grep -c "\.send") -gt 30 ]; do
        sleep 30
      done
      while [ $(ps -a | grep jrender | grep -c java) -gt 3 ]; do
		    sleep 1
      done
  	  if [ -e hold ]; then
    		echo "Holding..."
			  while [ -e hold ]; do
  				sleep 10
  			done
  			echo "Resuming"
    		break
    	fi
      tx=$(echo $file | cut -f 1 -d'-')
      ty=$(echo $file | cut -f 2 -d'-')
      z=$(echo $file | cut -f 3 -d'-')
      z=$(echo $z | cut -f 1 -d'.')
      java -jar jrender.jar tmp/ tiles/ $z $tx $ty 2>/dev/null
      echo "$(date) rendering $z $tx $ty" >> log.txt      
      rm tmp/$file
  	done
  fi
done
