#!/bin/bash

while true; do
	if [ $(ls tmp | grep -c '.send') -ne 0 ]; then
		for file in $(ls tmp | grep '.send'); do
  		if $(sftp -q -B 131072 -b tmp/$file 195.37.132.70 >/dev/null); then
    		rm tmp/$file
	    	echo $(date) $file sent
	    fi
		done
	fi
  sleep 2
done
